- name:             Bouwgeld Deposit Wallet
  blockchain_key:   bgd-main
  currency_id:      bgd
  # Address where deposits will be collected to.
  address:          'Tc2BM7gp8mKgJPPxLAadLAHteNQwhFwwuf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             deposit    # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1          # Number of signatures required for performing withdraw.
  max_balance:      0.0
  status:           active
  gateway:          bouwgeldd  # Gateway client name.
  settings:
    #
    # Bouwgeldd gateway client settings.
    uri:          http://user:password@127.0.0.1:19332

- name:             Bouwgeld Hot Wallet
  blockchain_key:   bgd-main
  currency_id:      bgd
  # Address where deposits will be collected to.
  address:          'Tc2BM7gp8mKgJPPxLAadLAHteNQwhFwwuf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             hot     # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1       # Number of signatures required for performing withdraw.
  max_balance:      5.0
  status:           active
  gateway:          bouwgeldd   # Gateway client name.
  settings:
    #
    # Bouwgeldd gateway client settings.
    uri:          http://user:password@127.0.0.1:19332

- name:             Bouwgeld Warm Wallet
  blockchain_key:   bgd-main
  currency_id:      bgd
  # Address where deposits will be collected to.
  address:          'Tc2BM7gp8mKgJPPxLAadLAHteNQwhFwwuf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             warm    # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1       # Number of signatures required for performing withdraw.
  max_balance:      50.0
  status:           active
  gateway:          bouwgeldd   # Gateway client name.
  settings:
    #
    # Bouwgeldd gateway client settings.
    uri:          http://user:password@127.0.0.1:19332
